CREATE TABLE IF NOT EXISTS Campaign(
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Name VARCHAR(32),
  Clicks INTEGER,
  Uniques INTEGER,
  Bounces INTEGER,
  Conversions INTEGER,
  Impressions INTEGER,
  TotalCost FLOAT,
  CTR FLOAT,
  CPA FLOAT,
  CPC FLOAT,
  CPM FLOAT,
  BounceRate FLOAT,
  Owner VARCHAR(32) REFERENCES User(Username) ON DELETE CASCADE ON UPDATE CASCADE
);
