CREATE TABLE IF NOT EXISTS Impression(
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  UserID INTEGER,
  Date DATE,
  CampaignID INTEGER NOT NULL,
  Gender TINYINT(1),
  Age TINYINT,
  Income INTEGER,
  Context INTEGER,
  Cost FLOAT,
  FOREIGN KEY (CampaignID) REFERENCES Campaign(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
