CREATE TABLE IF NOT EXISTS Ownership(
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Username VARCHAR(32) NOT NULL,
  CampaignID INTEGER NOT NULL,
  FOREIGN KEY (Username) REFERENCES User(Username),
  FOREIGN KEY (CampaignID) REFERENCES Campaign(ID)
);