CREATE TABLE IF NOT EXISTS Session(
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  UserID INTEGER,
  Date DATE,
  ExitDate DATE,
  Pages INTEGER,
  Conversion BOOLEAN,
  CampaignID INTEGER NOT NULL,
  Click INTEGER NOT NULL,
  FOREIGN KEY (CampaignID) REFERENCES Campaign(ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Click) REFERENCES Click(ID) ON DELETE CASCADE ON UPDATE CASCADE
);