CREATE TABLE IF NOT EXISTS Viewership(
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Username VARCHAR(32) NOT NULL,
  CampaignID INTEGER NOT NULL,
  FOREIGN KEY (Username) REFERENCES User(Username) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (CampaignID) REFERENCES Campaign(ID) ON DELETE CASCADE ON UPDATE CASCADE
);